wekan:
  restart: always
  image: mquandalle/wekan
  ports:
    - 80:80
  environment:
    MONGO_URL: mongodb://db
    ROOT_URL: http://example.com
  links:
    - wekan-db:db

wekan-db:
  restart: always
  image: mongo


cadvisor:
  restart: always
  image: google/cadvisor
  ports:
    - 8080:8080
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
