registry:
  image: registry
  ports:
    - "5000:5000"

jenkins:
  image: jenkins
  ports:
    - "8080:8080"
  volumes:
    - "/var/jenkins"

taskboard:
  image: mirweb/taskboard
  ports:
    - "4000:80"

gogs:
  image: codeskyblue/docker-gogs
  ports:
    - "3000:3000"
  volumes:
    - "/var/gogs:/data"
#
dockerboard:
  image: dockerboard/dockerboard
  ports:
    - "8001:8001"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

# docker run --name jenkins     -d --restart=always -p 8080:8080 -v /var/jenkins jenkins
# docker run --name registry    -d --restart=always -p 5000:5000 registry
# docker run --name taskboard   -d --restart=always -p 4000:80 mirweb/taskboard
# docker run --name gogs        -d --restart=always -p 3000:3000 -v /var/gogs:/data codeskyblue/docker-gogs
# docker run --name dockerboard -d --restart=always -p 8001:8001 -v /var/run/docker.sock:/var/run/docker.sock --restart=always   dockerboard/dockerboard
